Controllers/GoalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Models;
using FinalProject.Models.ViewModels;
using FinalProject.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class GoalsController : Controller
    {

        public WorkoutService _service;
        private readonly UserManager<ApplicationUser> _userService;
        private readonly IAuthorizationService _authService;

        public GoalsController(WorkoutService service,
            UserManager<ApplicationUser> userService,
            IAuthorizationService authService)
        {
            _service = service;
            _userService = userService;
            _authService = authService;
        }
        public async Task<IActionResult> Index()
        {
            var appUser = await _userService.GetUserAsync(User);
            var models = _service.GetGoals(appUser);

            return View(models);
        }

        public IActionResult Create()
        {
            return View(new CreateGoalsCommand());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGoalsCommand command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var appUser = await _userService.GetUserAsync(User);
                    var id = _service.CreateGoal(command, appUser);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError(
                    string.Empty,
                    "An error occured saving the goal"
                    );
            }
            return View(command);
        }

        public IActionResult Edit(int id)
        {
            var model = _service.GetGoalForUpdate(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Models;
using FinalProject.Models.ViewModels;
using FinalProject.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    [Authorize]
    public class WorkoutController : Controller
    {

        private readonly WorkoutService _service;
        private readonly UserManager<ApplicationUser> _userService;
        private readonly IAuthorizationService _authService;

        public WorkoutController(WorkoutService service,
            UserManager<ApplicationUser> userService,
            IAuthorizationService authService)
        {
            _service = service;
            _userService = userService;
            _authService = authService;
        }

        public async Task<IActionResult> Index()
        {
            var appUser = await _userService.GetUserAsync(User);
            var models = _service.GetPersonalWorkouts(appUser);
            return View(models);
        }

        public IActionResult GlobalWorkouts()
        {
            var models = _service.GetWorkouts();
            return View(models);
        }

        public async Task<IActionResult> View(int id)
        {
            var model = _service.GetWorkoutDetailed(id);
            if(model == null)
            {
                return NotFound();
            }

            var workout = _service.GetWorkout(id);
            var isAuthorized = await _authService.AuthorizeAsync(User, workout, "CanManageWorkout");
            model.CanEditWorkout = isAuthorized.Succeeded;
            return View(model);
        }

        public async Task<IActionResult> ViewGlobal(int id)
        {
            var model = _service.GetWorkoutDetailed(id);
            if (model == null)
            {
                return NotFound();
            }

            var workout = _service.GetWorkout(id);
            var isAuthorized = await _authService.AuthorizeAsync(User, workout, "CanManageWorkout");
            model.CanEditWorkout = isAuthorized.Succeeded;
            return View(model);
        }

        public IActionResult Create()
        {
            return View(new CreateWorkoutSummaryCommand());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWorkoutSummaryCommand command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var appUser = await _userService.GetUserAsync(User);
                    var id = _service.CreateWorkoutSummary(command, appUser);
                    return RedirectToAction(nameof(View), new { id = id });
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError(
                    string.Empty,
                    "An error occured saving the workout"
                    );
            }

            return View(command);
        }

        public IActionResult Edit(int id)
        {
            var model = _service.GetWorkoutForUpdate(id);
            if(model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(UpdateWorkoutCommand command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _service.UpdateWorkout(command);
                    return RedirectToAction(nameof(View), new { id = command.Id });
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError(
                    string.Empty,
                    "An error occured saving the workout"
                    );
            }
            return View(command);
        }

        
        [HttpPost]
        public IActionResult DeleteWorkout(int id)
        {
            _service.DeleteWorkout(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteWorkoutGlobal(int id)
        {
            _service.DeleteWorkout(id);
            return RedirectToAction(nameof(GlobalWorkouts));
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/images/banner1.jpg" alt="GymPic1" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Create a new Workout
                        <a asp-area="" asp-controller="Workout" asp-action="Create" class="btn btn-default">
                            Create Workout
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/banner2.jpg" alt="GymPic2" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        Set a new Goal
                        <a asp-area="" asp-controller="Goals" asp-action="Index" class="btn btn-default">
                            Set Goal
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/banner3.jpg" height="50%" width="100%" alt="GymPic3" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <p>
                        See past Workouts and Goals
                        <a asp-area="" asp-controller="Workout" asp-action="Index" class="btn btn-default">
                            See Archives
                            </a>
</p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h2><a class="btn btn-default" asp-area="" asp-controller="Workout" asp-action="Create">New Workout</a></h2>
            <ul>
                <li>Create a new Workout</li>
                <li>Edit an existing Workout</li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2 style="margin-left: 5% "><a class="btn btn-default" asp-area="" asp-controller="Goals" asp-action="Index">Goals</a></h2>
            <ul>
                <li>Create Goals</li>
                <li>Edit Goals</a></li>
            </ul>
        </div>

        <div class="col-md-3">
            <h2><a class="btn btn-default" asp-area="" asp-controller="Workout" asp-action="Index">Archives</a></h2>
            <ul>
                <li>See past Workouts</li>
                <li>See past Goals</li>
            </ul>
        </div>

        <div class="col-md-3">
            <h2><a class="btn btn-default" asp-area="" asp-controller="Workout" asp-action="GlobalWorkouts">Global Workouts</a></h2>
            <ul>
                <li>View Workouts of Other Users</li>
                <li>See How You Stack Up</li>
            </ul>
        </div>
    </div>